version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/smartcompost.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - frontend
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: mjannello
      DB_PASSWORD: mypassword
      DB_NAME: smartcompost_db
      CONFIG_PATH: /app/config/config.yml
    ports:
      - "8080:8080"
    volumes:
      - /var/log/web:/var/log/web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: smartcompost_db
      MYSQL_USER: mjannello
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /var/log/mysql:/var/log/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"
    volumes:
      - /var/log/frontend:/var/log/frontend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/var/loki
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"

volumes:
  db-data:
  loki-data:
  grafana-data:
