version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/smartcompost.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - web

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: mjannello
      DB_PASSWORD: mypassword
      DB_NAME: smartcompost_db
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: smartcompost_db
      MYSQL_USER: mjannello
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: ./frontend/.env.local
    ports:
      - "3000:3000"

volumes:
  db-data:
