version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:contraseña@postgres:5432/nombre_de_la_base_de_datos


  db:
    image: postgres:latest  # Cambia esto según tu configuración de base de datos PostgreSQL
    environment:
      POSTGRES_PASSWORD: yourpassword  # Configura la contraseña de la base de datos
