version: '3'
services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Mapea el puerto del contenedor al puerto local
    depends_on:
      - db
    command: [ "wait-for-it.sh", "db:5432", "--", "python", "init_app.py" ]
    environment:
      DATABASE_URL: postgresql://mjannello:mypassword@db:5432/smartcompost_db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mjannello
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: smartcompost_db
    ports:
      - "5432:5432"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Usa el Dockerfile del frontend
    ports:
      - "3000:3000"
