server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log

  - job_name: web
    static_configs:
      - targets:
          - localhost
        labels:
          job: web
          __path__: /var/log/web/web.log

  - job_name: frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          __path__: /var/log/frontend*.log
  - job_name: db
    static_configs:
      - targets:
          - localhost
        labels:
          job: db
          __path__: /var/log/mysql/*.log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

